### PR TITLE
Add Makefile and static tests

### PR DESCRIPTION
**Pull request by okurz**

### CODE REVIEW

**Comment by okurz** [comment]
missing dependencies to execute perlcritic, on it

**Comment by okurz** [comment]
I guess we should use a dependencies.yaml also in this project itself, WDYT?

**Comment by Martchus** [comment]
I would only use it if it helps to reduce redundancy (e.g. if dependencies would otherwise be specified in multiple places with no clear source of truth). However, it looks like we'd only specify them here in one place (`sudo apt-get -y install libperl-critic-perl`). I also think that our current approach with `dependencies.yaml` doesn't solve transforming dependencies into Ubuntu-style package names.

**Comment by okurz** [comment]
> I would only use it if it helps to reduce redundancy (e.g. if dependencies would otherwise be specified in multiple places with no clear source of truth). However, it looks like we'd only specify them here in one place (`sudo apt-get -y install libperl-critic-perl`). I also think that our current approach with `dependencies.yaml` doesn't solve transforming dependencies into Ubuntu-style package names.

No, it wouldn't. But we could define dependencies and then use cpan and also define a full blown spec file which specifies dependencies to build which we then pull in in a dedicated CI container. Doesn't sound lightweight though. But we need more than just `libperl-critic-perl` as we need other perlcritic modules.

**Comment by perlpunk** [comment]
This is obsolete

**Comment by okurz** [comment]
Actually not entirely obsolete. I rebased and now created
* #46

**Pull request closed without merging**
