### PR TITLE
workflows/commit_message_checker.yml: Fix file based prefix

### PR DESCRIPTION
**Pull request by foursixnine**
Follow up to: https://github.com/os-autoinst/os-autoinst/pull/1788 so that repos are in sync

### CODE REVIEW

**Comment by pevik** [comment]
LGTM, thanks for backporting this change.

**Review by Martchus — APPROVED** [review]

**Comment by pevik** [comment]
Added also to https://github.com/os-autoinst/openQA/pull/4255

**Comment by pevik** [comment]
I suppose .github/workflows/commit_message_checker.yml cannot be shared from this repository to https://github.com/os-autoinst/os-autoinst and https://github.com/os-autoinst/openQA, right?

**Comment by okurz** [comment]
> I suppose .github/workflows/commit_message_checker.yml cannot be shared from this repository to https://github.com/os-autoinst/os-autoinst and https://github.com/os-autoinst/openQA, right?

well, we tried but could not find a way so far.

**Comment by foursixnine** [comment]
> > I suppose .github/workflows/commit_message_checker.yml cannot be shared from this repository to https://github.com/os-autoinst/os-autoinst and https://github.com/os-autoinst/openQA, right?
> 
> well, we tried but could not find a way so far.

I'm guessing you've already looked into

-  github submodules + deploy hook?
-  fetching raw files from the repo directly (https://github.com/os-autoinst/openQA/blob/2895850f3b46ca8bccca29b38e29657784719292/tools/generate-documentation#L139)

?

**Comment by okurz** [comment]
@BillAnastasiadis you looked into this, did/can you try the above

**Comment by foursixnine** [comment]
I guess mergify isn't enabled for this repo right?

**Review by pevik — APPROVED** [review]

**Comment by pevik** [comment]
> > I suppose .github/workflows/commit_message_checker.yml cannot be shared from this repository to https://github.com/os-autoinst/os-autoinst and https://github.com/os-autoinst/openQA, right?
> 
> well, we tried but could not find a way so far.

Thanks for info. I'll probably leave this one for @BillAnastasiadis, but I might have look into unifying `tools/tidy` and put it into this repository.

**Comment by okurz** [comment]
> I guess mergify isn't enabled for this repo right?

no, it isn't

**Comment by foursixnine** [comment]
> > I guess mergify isn't enabled for this repo right?
> 
> no, it isn't

self merge then?

**Comment by okurz** [comment]
I awaited a response from @BillAnastasiadis

**Pull request merged**
