### PR TITLE
Update tidy version to 20240202

### PR DESCRIPTION
**Pull request by b10n1k**

### CODE REVIEW

**Review by Martchus — CHANGES_REQUESTED** [review]
The version also needs to be adjusted in the cpan file.

**Comment by perlpunk** [comment]
The selftest for make update-deps is missing in this repo.
I would like to fix all this, I think it will be easier. See #43

**Review by okurz — APPROVED** [review]

**Review by perlpunk — CHANGES_REQUESTED** [review]
We don't have that version in openSUSE yet.

**Review by okurz — CHANGES_REQUESTED** [review]
https://github.com/os-autoinst/os-autoinst-common/pull/41#pullrequestreview-1866032224

**Comment by kalikiana** [comment]
I assume #52 supersedes this

**Pull request closed without merging**
